micronaut:
  application:
    name: clinic
  server:
    host: ${APP_HOST}
    port: ${APP_PORT}
    context-path: /clinic
netty:
  default:
    allocator:
      max-order: 3

datasources:
  default:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    schema-generate: NONE

r2dbc:
  datasources:
    default:
      url: r2dbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
      username: ${DB_USERNAME}
      password: ${DB_PASSWORD}

liquibase:
  datasources:
    default:
      enabled: true
      change-log: classpath:/db/liquibase-changlog.xml

endpoints:
  liquibase:
    enabled: true
    sensitive: false
