micronaut:
  security:
    intercept-url-map:
      - pattern: /clinic/graphql**
        httpMethod: POST
        access:
          - isAnonymous()
      - pattern: /clinic/graphiql**
        httpMethod: GET
        access:
          - isAnonymous()

liquibase:
  datasources:
    default:
      drop-first: true
