micronaut:
  application:
    name: clinic
netty:
  default:
    allocator:
      max-order: 3

datasources:
  default:
    url: jdbc:postgresql://postgres:5432/postgres
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
    dialect: POSTGRES
    schema-generate: NONE

liquibase:
  datasources:
    default:
      enabled: true
      change-log: classpath:/db/liquibase-changlog.xml
