micronaut:
  application:
    name: clinic
netty:
  default:
    allocator:
      max-order: 3

datasources:
  default:
    url: jdbc:postgresql://postgres:5432/postgres
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    schema-generate: NONE

r2dbc:
  datasources:
    default:
      url: r2dbc:postgresql://postgres:5432/postgres
      username: ${DB_USERNAME}
      password: ${DB_PASSWORD}

liquibase:
  datasources:
    default:
      enabled: true
      change-log: classpath:/db/liquibase-changlog.xml

endpoints:
  liquibase:
    enabled: true
    sensitive: false
