micronaut:
  application:
    name: clinic
  server:
    host: ${APP_HOST}
    port: ${APP_PORT}
    context-path: /clinic
  router:
    static-resources:
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /swagger/**
      swagger-ui:
        paths: classpath:META-INF/swagger/views/swagger-ui
        mapping: /swagger-ui/**
      redoc:
        paths: classpath:META-INF/swagger/views/redoc
        mapping: /redoc/**
      rapidoc:
        paths: classpath:META-INF/swagger/views/rapidoc
        mapping: /rapidoc/**
  security:
    authentication: bearer
    token:
      jwt:
        signatures:
          secret:
            generator:
              secret: ${JWT_ACCESS_TOKEN_SECRET}
        generator:
          refresh-token:
            secret: ${JWT_REFRESH_TOKEN_SECRET}

netty:
  default:
    allocator:
      max-order: 3

datasources:
  default:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    schema-generate: NONE

r2dbc:
  datasources:
    default:
      url: r2dbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
      username: ${DB_USERNAME}
      password: ${DB_PASSWORD}
      schema-generate: NONE

liquibase:
  datasources:
    default:
      enabled: true
      change-log: classpath:/db/changelog/db.changelog-main.xml
      contexts: ${MICRONAUT_ENVIRONMENTS}

endpoints:
  liquibase:
    enabled: false
    sensitive: false

graphql:
  enabled: true
  graphiql:
    enabled: true
