micronaut:
  application:
    name: clinic
  server:
    host: ${APP_HOST}
    port: ${APP_PORT}
    context-path: /clinic
  router:
    static-resources:
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /swagger/**
      swagger-ui:
        paths: classpath:META-INF/swagger/views/swagger-ui
        mapping: /swagger-ui/**
      redoc:
        paths: classpath:META-INF/swagger/views/redoc
        mapping: /redoc/**
      rapidoc:
        paths: classpath:META-INF/swagger/views/rapidoc
        mapping: /rapidoc/**
netty:
  default:
    allocator:
      max-order: 3

datasources:
  default:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    schema-generate: NONE

r2dbc:
  datasources:
    default:
      url: r2dbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
      username: ${DB_USERNAME}
      password: ${DB_PASSWORD}

liquibase:
  datasources:
    default:
      enabled: false
      change-log: classpath:/db/changelog/db.changelog-main.xml

endpoints:
  liquibase:
    enabled: false
    sensitive: false
