@baseUrl = http://{{$processEnv APP_HOST}}:{{$processEnv APP_PORT}}/clinic
@accessToken = {{login.response.body.$.access_token}}
@refreshToken = {{login.response.body.$.refresh_token}}

# @name login
POST {{baseUrl}}/login
Accept: application/json
Content-Type: application/json

{
  "username": "admin1",
  "password": "p@ssw0rd"
}

###

# @name refreshToken
POST {{baseUrl}}/oauth/access_token
Accept: application/json
Content-Type: application/json

{
  "refresh_token": "eyJhbGciOiJIUzI1NiJ9.MDUxNTZhNDItNTcyYy00ODI5LThhOTAtYzM0ZTA3NTc4MzU0.sSHSBKViHosU79kZDV0bxTpRLvP1Gaqi5V7Vs4lLoFU",
  "grant_type": "refresh_token"
}

###

# @name getAuthenticatedUsername
GET {{baseUrl}}
Accept: text/plain
Content-Type: text/plain
Authorization: Bearer {{accessToken}}
