@baseUrl = http://{{$processEnv APP_HOST}}:{{$processEnv APP_PORT}}/clinic/v1/user
@userId = {{create.response.body.$.id}}
@accessToken = eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJzaGVybG9jayIsIm5iZiI6MTY2MjcyNTc5Mywicm9sZXMiOltdLCJpc3MiOiJjbGluaWMiLCJleHAiOjE2NjI3MjkzOTMsImlhdCI6MTY2MjcyNTc5M30.G8yXhdbCWuUUvo-oN9Eb0etn32hQL-YCgypbtveNU00

// @name create
POST {{baseUrl}}
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "id": "anas",
  "password": "p@ssw0rd",
  "fullName": "Anas Juwaidi"
}

###

// @name update
PUT {{baseUrl}}/{{userId}}
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "id": "anas",
  "fullName": "Anas Juwaidi Mohd Jeffry",
  "version": 0
}

###

// @name delete
DELETE {{baseUrl}}/{{userId}}
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "id": "anas",
  "version": 1
}
