@baseUrl = http://{{$processEnv APP_HOST}}:{{$processEnv APP_PORT}}/clinic/v1/user

// @name create
POST {{baseUrl}}
Accept: application/json
Content-Type: application/json
Accept-Language: en

{
  "id": "anas",
  "fullName": "Anas Juwaidi"
}
